---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-ctf-openshell-crd
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/eformat/data-agent-ctf.git
    targetRevision: main
    path: applications/openshell/crd
  destination:
    server: https://kubernetes.default.svc
    namespace: openshell
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-ctf-openshell
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/nvidia/openshell/helm-chart
      chart: openshell
      targetRevision: "0.0.62"
      helm:
        releaseName: openshell
        valueFiles:
          - $values/applications/openshell/helm-values/values.yaml
    - repoURL: https://github.com/eformat/data-agent-ctf.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/eformat/data-agent-ctf.git
      targetRevision: main
      path: applications/openshell/routes
    - repoURL: https://github.com/eformat/data-agent-ctf.git
      targetRevision: main
      path: applications/openshell/netpol
  destination:
    server: https://kubernetes.default.svc
    namespace: openshell
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
