---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-ctf
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/eformat/data-agent-ctf.git
    targetRevision: main
    path: app-of-apps/apps
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: data-agent-ctf
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
