apiVersion: apps/v1
kind: Deployment
metadata:
  name: __PLACEHOLDER__
spec:
  template:
    spec:
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
