{{- range $dept := list "finance" "sales" "ops" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: retail-{{ $dept }}
  annotations:
    haproxy.router.openshift.io/timeout: "3600s"
spec:
  host: retail-{{ $dept }}.{{ $.Values.appsDomain }}
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: grpc
  to:
    kind: Service
    name: openshell
{{- end }}
