---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keycloak-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-ca
spec:
  isCA: true
  secretName: keycloak-ca-secret
  commonName: keycloak-ca
  issuerRef:
    name: keycloak-selfsigned
    kind: Issuer
  duration: 87600h
  renewBefore: 720h
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keycloak-ca-issuer
spec:
  ca:
    secretName: keycloak-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
spec:
  secretName: keycloak-tls
  issuerRef:
    name: keycloak-ca-issuer
    kind: Issuer
  dnsNames:
    - keycloak-service
    - keycloak-service.data-agent-ctf.svc
    - keycloak-service.data-agent-ctf.svc.cluster.local
  duration: 8760h
  renewBefore: 720h
