---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: keycloak-tls
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
