---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: retail-finance
  annotations:
    haproxy.router.openshift.io/timeout: "3600s"
spec:
  host: retail-finance.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: grpc
  to:
    kind: Service
    name: openshell
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: retail-sales
  annotations:
    haproxy.router.openshift.io/timeout: "3600s"
spec:
  host: retail-sales.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: grpc
  to:
    kind: Service
    name: openshell
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: retail-ops
  annotations:
    haproxy.router.openshift.io/timeout: "3600s"
spec:
  host: retail-ops.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: grpc
  to:
    kind: Service
    name: openshell
