---
image:
  repository: quay.io/eformat/openshell-gateway
  tag: 0.0.62-h2ws
certManager:
  enabled: true
  serverDnsNames:
    - openshell
    - openshell.openshell.svc
    - openshell.openshell.svc.cluster.local
    - localhost
    - openshell.localhost
    - "*.openshell.localhost"
    - "*.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com"
server:
  auth:
    allowUnauthenticatedUsers: true
  tls:
    clientCaSecretName: ""
pkiInitJob:
  serverDnsNames:
    - "*.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com"
podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsUser: 1000
service:
  type: ClusterIP
tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
