---
image:
  repository: quay.io/eformat/openshell-gateway
  tag: 0.0.69
  pullPolicy: Always
certManager:
  enabled: true
  serverDnsNames:
    - openshell
    - openshell.openshell.svc
    - openshell.openshell.svc.cluster.local
    - localhost
    - openshell.localhost
    - "*.openshell.localhost"
    - "*.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com"
    - openshell.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com
grpcRoute:
  enabled: false
pkiInitJob:
  serverDnsNames:
    - "*.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com"
    - openshell.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com
podSecurityContext:
  fsGroup: null
securityContext:
  runAsUser: null
server:
  auth:
    allowUnauthenticatedUsers: true
  tls:
    clientCaSecretName: ""
  oidc:
    issuer: "https://keycloak-openshell.apps.prelude-m6wl4-jf54l.sandbox1832.opentlc.com/realms/retail-ctf"
    audience: "openshell-cli"
    rolesClaim: "realm_access.roles"
service:
  type: ClusterIP
tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
