---
image:
  repository: quay.io/eformat/openshell-gateway
  tag: v0.0.85
  pullPolicy: Always
grpcRoute:
  enabled: false
podSecurityContext:
  fsGroup: null
securityContext:
  runAsUser: null
server:
  auth:
    allowUnauthenticatedUsers: true
  tls:
    clientCaSecretName: ""
  oidc:
    audience: "openshell-cli"
    rolesClaim: "realm_access.roles"
  providerTokenGrants:
    spiffe:
      enabled: true
      workloadApiSocketPath: /spiffe-workload-api/spire-agent.sock
service:
  type: ClusterIP
tolerations:
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
