---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-ctf-keycloak-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitRepo }}
    targetRevision: {{ .Values.gitRevision }}
    path: applications/keycloak/base
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-ctf-keycloak
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitRepo }}
    targetRevision: {{ .Values.gitRevision }}
    path: applications/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  ignoreDifferences:
    - group: ""
      kind: Service
      name: keycloak-service
      jsonPointers:
        - /metadata/annotations
        - /spec/selector
    - group: k8s.keycloak.org
      kind: Keycloak
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
