---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-ctf-retail-mcp
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.gitRepo }}
    targetRevision: {{ .Values.gitRevision }}
    path: applications/retail-mcp
    helm:
      valuesObject:
        appsDomain: {{ .Values.appsDomain }}
        namespace: {{ .Values.namespace }}
        realmName: {{ .Values.realmName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
