---
# TODO: copy from ~/git/trino-chart/nessie/
# Nessie catalog server for Iceberg metadata
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  labels:
    app: nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
      containers:
        - name: nessie
          image: ghcr.io/projectnessie/nessie@sha256:1fc1e7d02a3d49827dd90c0cd41412303b525321d7fc5497e57d78693f8c3306
          ports:
            - containerPort: 19120
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nessie
spec:
  selector:
    app: nessie
  ports:
    - port: 19120
      targetPort: 19120
